word service layer test NullPointerException
java.lang.NullPointerException: Cannot invoke "side.project.FHM.dao.WordDao.getALlWords()" because "this.wordDao" is null